//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdhocUserPackage
    {
        public AdhocUserPackage()
        {
            this.AdhocUserPackagesAddons = new HashSet<AdhocUserPackagesAddon>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int PackageId { get; set; }
        public int CarId { get; set; }
        public System.DateTime SubscribedDate { get; set; }
        public decimal ActualPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal PriceWithAddOns { get; set; }
        public decimal DiscountPrice { get; set; }
        public string Ipaddress { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public int ExistingPackageId { get; set; }
        public bool PaymentRecieved { get; set; }
        public bool Processed { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TipAmount { get; set; }
    
        public virtual CarUser CarUser { get; set; }
        public virtual Package Package { get; set; }
        public virtual UserPackage UserPackage { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AdhocUserPackagesAddon> AdhocUserPackagesAddons { get; set; }
    }
}
