//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AdhocUserPackages = new HashSet<AdhocUserPackage>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.CarServiceEntries = new HashSet<CarServiceEntry>();
            this.CarUsers = new HashSet<CarUser>();
            this.CrewAdminMembers = new HashSet<CrewAdminMember>();
            this.LeaderMembers = new HashSet<LeaderMember>();
            this.LeaderMembers1 = new HashSet<LeaderMember>();
            this.CrewAdminMembers1 = new HashSet<CrewAdminMember>();
            this.LeaderCarJobs = new HashSet<LeaderCarJob>();
            this.UserPackages = new HashSet<UserPackage>();
            this.UserTransactions = new HashSet<UserTransaction>();
            this.WorkDones = new HashSet<WorkDone>();
            this.WorkDones1 = new HashSet<WorkDone>();
            this.CarServiceEntries1 = new HashSet<CarServiceEntry>();
            this.WorkerGarages = new HashSet<WorkerGarage>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.PaypalAutoPayments = new HashSet<PaypalAutoPayment>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Address { get; set; }
        public int State { get; set; }
        public int City { get; set; }
        public string Pincode { get; set; }
        public int Balance { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<AdhocUserPackage> AdhocUserPackages { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual City City1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual ICollection<CarServiceEntry> CarServiceEntries { get; set; }
        public virtual ICollection<CarUser> CarUsers { get; set; }
        public virtual ICollection<CrewAdminMember> CrewAdminMembers { get; set; }
        public virtual ICollection<LeaderMember> LeaderMembers { get; set; }
        public virtual ICollection<LeaderMember> LeaderMembers1 { get; set; }
        public virtual ICollection<CrewAdminMember> CrewAdminMembers1 { get; set; }
        public virtual ICollection<LeaderCarJob> LeaderCarJobs { get; set; }
        public virtual ICollection<UserPackage> UserPackages { get; set; }
        public virtual ICollection<UserTransaction> UserTransactions { get; set; }
        public virtual ICollection<WorkDone> WorkDones { get; set; }
        public virtual ICollection<WorkDone> WorkDones1 { get; set; }
        public virtual ICollection<CarServiceEntry> CarServiceEntries1 { get; set; }
        public virtual ICollection<WorkerGarage> WorkerGarages { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<PaypalAutoPayment> PaypalAutoPayments { get; set; }
    }
}
