//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarServiceEntry
    {
        public int Id { get; set; }
        public string CarOwnerId { get; set; }
        public int CarId { get; set; }
        public string WorkerId { get; set; }
        public int PackageId { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual CarUser CarUser { get; set; }
        public virtual Package Package { get; set; }
    }
}
