//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageTeam
    {
        public int Id { get; set; }
        public int GarageId { get; set; }
        public string Title { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
