//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderCarJob
    {
        public int Id { get; set; }
        public string Day { get; set; }
        public int GarageId { get; set; }
        public string LeaderId { get; set; }
        public int CarId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CarUser CarUser { get; set; }
        public virtual Garage Garage { get; set; }
    }
}
