//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.AdhocUserPackages = new HashSet<AdhocUserPackage>();
            this.CarServiceEntries = new HashSet<CarServiceEntry>();
            this.Package_Services = new HashSet<Package_Services>();
            this.UserPackages = new HashSet<UserPackage>();
            this.WorkDones = new HashSet<WorkDone>();
        }
    
        public int PackageId { get; set; }
        public string Package_Name { get; set; }
        public string Package_Description { get; set; }
        public decimal Package_Price { get; set; }
        public System.DateTime CreateDt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<AdhocUserPackage> AdhocUserPackages { get; set; }
        public virtual ICollection<CarServiceEntry> CarServiceEntries { get; set; }
        public virtual ICollection<Package_Services> Package_Services { get; set; }
        public virtual ICollection<UserPackage> UserPackages { get; set; }
        public virtual ICollection<WorkDone> WorkDones { get; set; }
    }
}
