//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Services
    {
        public int PackageServiceId { get; set; }
        public int PackageID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Service Service { get; set; }
    }
}
