//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalLog
    {
        public int LogId { get; set; }
        public string UserId { get; set; }
        public string ApiSatus { get; set; }
        public string ResponseError { get; set; }
        public string ResponseRedirectURL { get; set; }
        public string ECToken { get; set; }
        public string BillingAggrementID { get; set; }
        public string TimeStamp { get; set; }
        public string CorrelationID { get; set; }
        public string ACK { get; set; }
        public Nullable<System.DateTime> ServerDate { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
    
        public virtual UserPackage UserPackage { get; set; }
    }
}
