//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.AdhocUserPackagesAddons = new HashSet<AdhocUserPackagesAddon>();
            this.Package_Services = new HashSet<Package_Services>();
            this.UserPackagesAddons = new HashSet<UserPackagesAddon>();
        }
    
        public int ServiceID { get; set; }
        public string Service_Name { get; set; }
        public string Service_Description { get; set; }
        public decimal Service_Price { get; set; }
        public System.DateTime CreateDt { get; set; }
        public string CreatedBy { get; set; }
        public bool IsAddOn { get; set; }
    
        public virtual ICollection<AdhocUserPackagesAddon> AdhocUserPackagesAddons { get; set; }
        public virtual ICollection<Package_Services> Package_Services { get; set; }
        public virtual ICollection<UserPackagesAddon> UserPackagesAddons { get; set; }
    }
}
