//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Cities = new HashSet<City>();
            this.Garages = new HashSet<Garage>();
        }
    
        public int Id { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Garage> Garages { get; set; }
    }
}
