//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string PaypalId { get; set; }
        public string Details { get; set; }
        public string Userid { get; set; }
        public string BillingAggrementID { get; set; }
        public string TrasactionID { get; set; }
        public string ReferenceID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UserPackage UserPackage { get; set; }
    }
}
