//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weekday
    {
        public Weekday()
        {
            this.GarrageWeekdays = new HashSet<GarrageWeekday>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GarrageWeekday> GarrageWeekdays { get; set; }
    }
}
